[package]
name = "vizcrush-downsample"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "LTTB, MinMaxLTTB, M4, LTOB downsampling algorithms"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
